### ISSUE TITLE
Error during adding products

### ISSUE THREAD

**Issue by Tychodewaard** [openstore-ecommerce/OpenStore#4]
During adding products, I encountered performance issues.
In the Event log (DNN 804) I got this error: I got it regarding process ID 51 (twice) and pricess ID 52 (twice). 
The fact that I got them twice might be due to the fact that I reloaded the page (?)

AbsoluteURL:/DesktopModules/NBright/NBrightBuy/XmlConnector.ashx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:5270a2fa-3452-409a-98ad-141266f26931

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:dGYxC/C3VKtvw5qTR8mN2w==

Message:Transaction (Process ID 52) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

StackTrace:

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(SqlConnection connection, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(String connectionString, CommandType commandType, String commandText, SqlParameter[] commandParameters)
   at Microsoft.ApplicationBlocks.Data.SqlHelper.ExecuteScalar(String connectionString, String spName, Object[] parameterValues)
   at Nevoweb.DNN.NBrightBuy.Components.SqlDataProvider.SqlDataProvider.Update(Int32 ItemId, Int32 PortalId, Int32 ModuleId, String TypeCode, String XMLData, String GUIDKey, DateTime ModifiedDate, String TextData, Int32 XrefItemId, Int32 ParentItemId, Int32 UserId, String Lang)
   at Nevoweb.DNN.NBrightBuy.Components.NBrightBuyController.Update(NBrightInfo objInfo)
   at Nevoweb.DNN.NBrightBuy.Components.CategoryData.AddNew()
   at Nevoweb.DNN.NBrightBuy.Components.CategoryData.LoadData(Int32 categoryId)
   at Nevoweb.DNN.NBrightBuy.Components.CategoryUtils.GetCategoryData(Int32 categoryId, String lang)
   at Nevoweb.DNN.NBrightBuy.Components.Category.CategoryFunctions.CategoryAdminAddNew(HttpContext context, String editType)
   at Nevoweb.DNN.NBrightBuy.Components.Clients.PropertyFunctions.ProcessCommand(String paramCmd, HttpContext context, String editlang)
   at Nevoweb.DNN.NBrightBuy.XmlConnector.ProcessRequest(HttpContext context)
InnerMessage:

InnerStackTrace:

Source:.Net SqlClient Data Provider

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

**Comment by leedavi** [comment]
did you have the browser open 2 times?  Or was this error shown on a single page going slow?

Could you have clicked the button multiple time?

Maybe we need to hide the action buttons when one is clicked?

**Comment by leedavi** [comment]
Cannot recreate and the button already does hide.  We need to recreate to get this.  I'll close this issue until we can prove there is a problem.
